default:
	replacefigs figures

prefix:
	cat figures.tex | replacefigs --figprefix figure_


dontcopy:
	replacefigs --dontcopyfigs figures.tex 

clean:
	rm -f Fig*pdf
	rm -f fig*pdf
	rm -f Fig*jpg
	rm -f fig*jpg
	rm -f Fig*png
	rm -f fig*png
